### ISSUE TITLE
Not loading correctly

### ISSUE THREAD

**Issue by phpfs** [nferro/homebridge-http-json#3]
Hello!

What does your plugin expect to find under the given URL, can you give a formatting example?
f.ex. {"temperature": "32.3","humidity":"50.6"}

Greetings, phpfs

**Comment by nferro** [comment]
I completely missed this notification... For the default config-section.json these would be the fields.

**Comment by r4zr1** [comment]
Hi!
Plz help, my temp/humidity sensor output:

`{"system":{"hostname":"ESP12F","uptime":4724,"rssi":-51,"freemem":31664},"sensors":{"bmet":22.8,"bmeh":47.8,"bmep":741.29,"dsw1":9.0}}`

dsw1 for street Temp
bmet and bmeh for room Temp Humidity

How config.json should look like?
with code below it doesn't work :(
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
	"accessory": "http-json",
	"service": "Thermostat",
	"name": "ESP8266",
	"url": "http://192.168.5.169/readjson",
	"sensors" : [
		{
			"name": "Temperature",
			"service": "TemperatureSensor",
			"caractheristic": "CurrentTemperature",
			"field": "dsw1"
		},
		{
			"name": "Humidity",
			"service": "HumiditySensor",
			"caractheristic": "CurrentRelativeHumidity",
			"field": "bmeh"
		}
	]
}`

**Comment by phpfs** [comment]
Hi :)

How source code looks for me, it is not possible to use your json output directly as your values are placed ‚under two keys‘.

Ex.:
{„temperature“: „32.5“, „humidity“: „60.8“}      -> Will work
{„sys“: {„temperature“: „32.5“, „humidity“: „60.8“} }    -> Won‘t work

You can either change the source code to allow „sys.temp“ to be parsed successfully or use a middle ware who maps the values as needed (Example 2 to Example 1).

I hope this helps :)

Greetings, phpfs
